### ISSUE TITLE
PM Review: Questions/Match

### ISSUE THREAD

**Issue by alisonscheng** [snakerabbit/jam#27]

**Comment by alisonscheng** [comment]
Questions that users have answered are on their profile page, and you can answer questions from own profile.  No match functionality yet, but that is in next MVP

**Comment by debsfong** [comment]
Please add functionality to edit your answers to questions! (Would be nice to also be able to edit the "about me" but lets leave that for if we have time)

**Comment by debsfong** [comment]
Please remove the "edit" pencil button since you do not have this functionality.

**Comment by debsfong** [comment]
Please also remove the "about me" page if you cannot edit it
