### ISSUE TITLE
PM Review: User Authentication

### ISSUE THREAD

**Issue by alisonscheng** [snakerabbit/jam#8]

**Comment by debsfong** [comment]
Styling is almost there. I would suggest finding a sharper image unless you're planning to put more on the login page. The submit button also looks a bit dated. 

I'm having trouble logging in and signing up :(

**Comment by debsfong** [comment]
Styling is better now! But weird things happen if you mess up signing in or logging in, and then try to sign/log in correctly. It's almost there!

**Comment by debsfong** [comment]
Last thing this needs is to clear errors! I'll mark it done after you've finished that. 

Clear errors should be called basically anytime you hit login or signup or direct to another page.

**Comment by alisonscheng** [comment]
@debsfong the errors are now clearing

**Comment by debsfong** [comment]
Looks great!
